// types.ts
// Shared TypeScript interfaces used across the entire MentorAI app.
// Every teammate imports from here — do not define types elsewhere.

// ── Primitive Types ───────────────────────────────────────────────────────────

/** The two subjects available in the app */
export type Subject = 'math' | 'ela';

/** Supported grade levels */
export type Grade = 6 | 7 | 8;

/** Supported display languages */
export type Language = 'en';

// ── Quiz ──────────────────────────────────────────────────────────────────────

/** A single multiple-choice question inside a lesson */
export interface Question {
  prompt:       string;    // The question text shown to the student
  choices:      string[];  // Always exactly 4 answer options
  correctIndex: number;    // Index (0–3) of the correct choice in choices[]
  hint:         string;    // One-sentence hint shown when student uses a hint token
  answered:     boolean;   // has the student seen this question?
  correct:      boolean;   // did they get it right?
  difficulty:   1 | 2 | 3; // used by Gemini to generate harder replacements
}

// ── Lesson ────────────────────────────────────────────────────────────────────

/**
 * A full lesson unit — either pre-written (isPreloaded: true)
 * or AI-generated by Gemini (isPreloaded: false).
 * Stored in IndexedDB so it's available completely offline.
 */
export interface Lesson {
  id?:          number;     // Auto-assigned by Dexie — never set this manually
  subject:     Subject;
  grade:       Grade;
  language:    Language;
  title:       string;     // Short display title e.g. "Introduction to Fractions"
  content:     string;     // 2–3 paragraphs of lesson text shown before the quiz
  questions:   Question[]; // 5 quiz questions for this lesson
  createdAt:   string;     // ISO date string e.g. "2026-04-25T19:00:00.000Z"
  isPreloaded: boolean;    // true = came from lessons/*.json, false = Gemini-generated
}

// ── Progress ──────────────────────────────────────────────────────────────────

/**
 * One quiz attempt by a student.
 * Saved to IndexedDB immediately after quiz completion — works fully offline.
 * Synced to the teacher dashboard when the device reconnects.
 */
export interface Progress {
  id?:          number;    // Auto-assigned by Dexie
  nickname:    string;    // Student's chosen nickname (no real names — privacy)
  lessonId:    number;    // References Lesson.id
  lessonTitle: string;    // Stored directly in case the lesson gets deleted later
  subject:     Subject;
  score:       number;    // 0–100 percentage score
  xpEarned:   number;    // XP awarded for this attempt (based on score)
  attempts:    number;    // How many tries the student needed to finish
  hintsUsed:   number;    // Number of hint tokens spent during this quiz
  completedAt: string;    // ISO date string
}

// ── Student Profile ───────────────────────────────────────────────────────────

/**
 * One profile per student, stored locally in IndexedDB.
 * No accounts, no login — identified only by nickname.
 * Updated by Person 3 after every quiz via updateProfile() in db.ts.
 */
export interface StudentProfile {
  id?:           number;   // Auto-assigned by Dexie
  nickname:     string;   // Chosen on first launch e.g. "StarCoder99"
  grade:        Grade;
  language:     Language; // Controls lesson language and UI language
  totalXP:      number;   // Cumulative XP across all subjects
  currentLevel: number;   // Calculated from totalXP — Person 3 owns this logic
  streak:       number;   // Consecutive days the student has been active
  lastActive:   string;   // ISO date string — used to calculate/reset streak
  mathXP:       number;   // XP earned specifically in math lessons
  elaXP:        number;   // XP earned specifically in ELA lessons
  lastProgressReport?: string;  // the ? means it can be undefined until first sync
  lastReportDate?:     string;
}

// ── Sync Queue ────────────────────────────────────────────────────────────────

/**
 * A pending API call that couldn't run because the device was offline.
 * Items are added to this table when offline and flushed in utils/offline.ts
 * once the device reconnects to WiFi.
 */
export interface SyncQueueItem {
  id?:        number;                    // Auto-assigned by Dexie
  type:      SyncType;                  // Determines which Gemini function to call
  payload:   Record<string, unknown>;   // Data passed to the Gemini function
  timestamp: number;                    // Date.now() — older items are processed first
  retries:   number;                    // Incremented on failure, max 3 before skipping
}

/** The types of Gemini calls that can be queued for later */
export type SyncType =
  | 'replace_question'  // Replace a correctly-answered question with a harder one
  | 'generate_lesson'   // Generate a new AI lesson and save it offline
  | 'progress_report'   // Generate a teacher summary for the dashboard
  | 'get_feedback';     // Get AI feedback on a student's written answer

// ── Gemini ────────────────────────────────────────────────────────────────────

/**
 * The shape Gemini must return when asked to generate a lesson.
 * gemini.ts parses the raw API response into this shape before saving.
 */
export interface GeminiLessonResponse {
  title:     string;
  content:   string;
  questions: Question[];
}

// ── App State ─────────────────────────────────────────────────────────────────

/**
 * Global UI state passed between screens by router.ts (Person 2).
 * Holds the active student profile, the current lesson being viewed,
 * and the live online/offline status.
 */
export interface AppState {
  profile:       StudentProfile | null; // null until student enters their nickname
  currentLesson: Lesson | null;         // null when on the dashboard screen
  isOnline:      boolean;               // mirrors navigator.onLine, updated by offline.ts
}